In [8]:
import numpy as np

# Create 1D array
arr = np.arange(7, 37)
print('1D Array:', arr)

# Reshape to 4x5 matrix
matrix = arr.reshape(5, 6)
print('4x5 Matrix:\n', matrix)

# Mean, Median, Std
print('Mean:', np.mean(arr))
print('Median:', np.median(arr))
print('Standard Deviation:', np.std(arr))

# Element-wise operations
arr2 = np.arange(31, 61)
print('Addition:', arr + arr2)
print('Multiplication:', arr * arr2)


1D Array: [ 7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30
 31 32 33 34 35 36]
4x5 Matrix:
 [[ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Mean: 21.5
Median: 21.5
Standard Deviation: 8.65544144839919
Addition: [38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84
 86 88 90 92 94 96]
Multiplication: [ 217  256  297  340  385  432  481  532  585  640  697  756  817  880
  945 1012 1081 1152 1225 1300 1377 1456 1537 1620 1705 1792 1881 1972
 2065 2160]
